class Config:
    INDIRECTION_COLUMN = 0
    RID_COLUMN = 1
    TIMESTAMP_COLUMN = 2
    SCHEMA_ENCODING_COLUMN = 3
    BASE_RID_COLUMN = 4
    USER_COLUMN_START = 5

    # COL_OFFSET = 5

    PAGE_CAPACITY = 4096 // 8